import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Building2, FileText, Mail, MapPin, MessageSquare, Newspaper, Zap } from 'lucide-react';
import { society } from '@/content/pages/home';
import contactContent from '@/content/pages/contact';
export const metadata: Metadata = { title: 'Contact | Delhi Fight Against Electricity Bills Society', description: 'Contact the Society about electricity-billing concerns, Society information, association collaboration and media enquiries.' };
const options = [
 { icon: Zap, title: 'Electricity Bill Concern', text: 'Need information about an electricity-billing issue?', label: 'Visit Bill Help', href: '/bill-help' },
 { icon: MessageSquare, title: 'General Enquiry', text: 'Questions regarding the Society, activities or documents.', label: 'Send an Enquiry', href: '#enquiry' },
 { icon: Building2, title: 'Association / Organisation', text: 'Interested in connecting or discussing a common electricity-related concern?', label: 'Contact the Society', href: '#enquiry' },
 { icon: Newspaper, title: 'Media Enquiry', text: 'Journalists and publications may contact the Society regarding activities and public information.', label: 'Make a Media Enquiry', href: '#enquiry' },
];
export default function ContactPage(){return <main id="main" className="contact-page">
 <section className="inner-hero contact-hero"><div className="container"><p className="eyebrow"><span/> Contact Us</p><h1>{contactContent.heroTitle}</h1><p className="inner-hero-lead">{contactContent.heroLead}</p><p className="contact-welcome">{contactContent.welcome}</p></div></section>
 <section className="section container contact-options"><div className="section-heading"><div><p className="eyebrow">Contact Options</p><h2>How Can We Help?</h2></div></div><div className="contact-options-grid">{options.map(({icon:Icon,title,text,label,href})=><article key={title}><Icon size={27} strokeWidth={1.5}/><h3>{title}</h3><p>{text}</p><Link href={href} className="text-link">{label}<ArrowRight size={17}/></Link></article>)}</div></section>
 <section id="enquiry" className="section contact-enquiry-section"><div className="container contact-enquiry-grid"><div className="contact-email-panel"><Mail size={32} strokeWidth={1.5}/><p className="eyebrow">Email Enquiries</p><h2>Write to Us</h2><p>For questions about Society activities, documents or electricity-billing initiatives, compose an email in your preferred mail app.</p><a href="mailto:?subject=Enquiry%20for%20Delhi%20Fight%20Against%20Electricity%20Bills%20Society" className="button">Open Email <Mail size={18}/></a><p className="contact-email-note">Opens your default email app. The recipient is left blank until the Society’s email address is confirmed.</p><p className="contact-support">For detailed electricity-billing concerns, <Link href="/bill-help">visit Bill Help</Link> to understand the information and supporting documents to prepare.</p></div>
 <aside className="contact-office"><div className="contact-office-heading"><MapPin size={29}/><p className="eyebrow">Registered Office</p></div><h2>Find Us in Delhi</h2><p className="contact-office-name">{society.name}</p><address>Plot No. 86, Pocket-C, Sector-2<br/>DSIIDC Bawana<br/>Delhi – 110039</address><dl><div><dt>Working Area</dt><dd>Delhi</dd></div><div><dt>Registration No.</dt><dd>{society.registration}</dd></div></dl><p className="contact-office-note">Public phone, email and office timings will be added once confirmed by the Society.</p><Link href="/about" className="text-link">About the Society <ArrowRight size={17}/></Link></aside></div></section>
 <section className="section container contact-important"><FileText size={30} strokeWidth={1.5}/><div><p className="eyebrow">Important Information</p><h2>Before You Contact Us</h2><p>The Society provides information, awareness and a platform for documenting electricity-related consumer concerns.</p><p>Submitting an issue to the Society does not automatically constitute a formal complaint to your electricity distribution company, DERC or another government/regulatory authority.</p><p>Consumers should continue to follow applicable official grievance procedures and retain complaint/reference numbers and supporting documents.</p><Link href="/bill-help" className="text-link">Explore Bill Help <ArrowRight size={17}/></Link></div></section>
 </main>;}
