import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Building2, FileText, MapPin, MessageSquare, Newspaper, Zap } from 'lucide-react';
import { society } from '@/content/home';
export const metadata: Metadata = { title: 'Contact | Delhi Fight Against Electricity Bills Society', description: 'Contact the Society about electricity-billing concerns, Society information, association collaboration and media enquiries.' };
const options = [
 { icon: Zap, title: 'Electricity Bill Concern', text: 'Need information about an electricity-billing issue?', label: 'Visit Bill Help', href: '/bill-help' },
 { icon: MessageSquare, title: 'General Enquiry', text: 'Questions regarding the Society, activities or documents.', label: 'Send an Enquiry', href: '#enquiry' },
 { icon: Building2, title: 'Association / Organisation', text: 'Interested in connecting or discussing a common electricity-related concern?', label: 'Contact the Society', href: '#enquiry' },
 { icon: Newspaper, title: 'Media Enquiry', text: 'Journalists and publications may contact the Society regarding activities and public information.', label: 'Make a Media Enquiry', href: '#enquiry' },
];
export default function ContactPage(){return <main id="main" className="contact-page">
 <section className="inner-hero contact-hero"><div className="container"><p className="eyebrow"><span/> Contact Us</p><h1>Get in Touch<br/>With the Society</h1><p className="inner-hero-lead">Have a question about our activities, want to share an electricity-billing concern, or represent an association interested in connecting with the Society?</p><p className="contact-welcome">We would like to hear from you.</p></div></section>
 <section className="section container contact-options"><div className="section-heading"><div><p className="eyebrow">Contact Options</p><h2>How Can We Help?</h2></div></div><div className="contact-options-grid">{options.map(({icon:Icon,title,text,label,href})=><article key={title}><Icon size={27} strokeWidth={1.5}/><h3>{title}</h3><p>{text}</p><Link href={href} className="text-link">{label}<ArrowRight size={17}/></Link></article>)}</div></section>
 <section id="enquiry" className="section contact-enquiry-section"><div className="container contact-enquiry-grid"><div className="contact-form-panel"><p className="eyebrow">Contact Form</p><h2>Send Us a Message</h2><p className="contact-form-intro">Please provide sufficient information for us to understand your enquiry. Fields marked * are required.</p><div className="contact-form-notice" id="contact-availability"><strong>Online enquiries are not open yet.</strong><p>The Society’s verified contact channel is being confirmed. This form does not send or save information at present.</p></div><form aria-describedby="contact-availability" className="contact-form"><div className="contact-field"><label htmlFor="contact-name">Full Name *</label><input id="contact-name" name="fullName" autoComplete="name" required maxLength={120}/></div><div className="contact-field"><label htmlFor="contact-mobile">Mobile Number *</label><input id="contact-mobile" name="mobile" type="tel" autoComplete="tel" required maxLength={25}/></div><div className="contact-field"><label htmlFor="contact-email">Email Address</label><input id="contact-email" name="email" type="email" autoComplete="email" maxLength={254}/></div><div className="contact-field"><label htmlFor="contact-area">Area / Locality</label><input id="contact-area" name="locality" autoComplete="address-level3" maxLength={150}/></div><div className="contact-field contact-field-wide"><label htmlFor="contact-type">Enquiry Type *</label><select id="contact-type" name="enquiryType" required defaultValue=""><option value="" disabled>Select an enquiry type</option>{['Electricity Bill','Society Information','Association Collaboration','Media','Membership','Other'].map(type=><option key={type}>{type}</option>)}</select></div><div className="contact-field contact-field-wide"><label htmlFor="contact-subject">Subject *</label><input id="contact-subject" name="subject" required maxLength={200}/></div><div className="contact-field contact-field-wide"><label htmlFor="contact-message">Message *</label><textarea id="contact-message" name="message" required rows={6} maxLength={5000}/></div><div className="contact-field-wide contact-send"><button type="button" className="button" disabled aria-describedby="contact-availability">Send Message <ArrowRight size={18}/></button><span>Sending will be available once contact details are confirmed.</span></div></form><p className="contact-support">For detailed electricity-billing concerns, <Link href="/bill-help">visit Bill Help</Link> to understand the information and supporting documents to prepare.</p></div>
 <aside className="contact-office"><div className="contact-office-heading"><MapPin size={29}/><p className="eyebrow">Registered Office</p></div><h2>Find Us in Delhi</h2><p className="contact-office-name">{society.name}</p><address>Plot No. 86, Pocket-C, Sector-2<br/>DSIIDC Bawana<br/>Delhi – 110039</address><dl><div><dt>Working Area</dt><dd>Delhi</dd></div><div><dt>Registration No.</dt><dd>{society.registration}</dd></div></dl><p className="contact-office-note">Public phone, email and office timings will be added once confirmed by the Society.</p><Link href="/about" className="text-link">About the Society <ArrowRight size={17}/></Link></aside></div></section>
 <section className="section container contact-important"><FileText size={30} strokeWidth={1.5}/><div><p className="eyebrow">Important Information</p><h2>Before You Contact Us</h2><p>The Society provides information, awareness and a platform for documenting electricity-related consumer concerns.</p><p>Submitting an issue to the Society does not automatically constitute a formal complaint to your electricity distribution company, DERC or another government/regulatory authority.</p><p>Consumers should continue to follow applicable official grievance procedures and retain complaint/reference numbers and supporting documents.</p><Link href="/bill-help" className="text-link">Explore Bill Help <ArrowRight size={17}/></Link></div></section>
 </main>;}
