'use client';
/* eslint-disable @next/next/no-img-element */
import { ArrowUpRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger } from '@/components/ui/dialog';
const articles = [
 { id:'procurement', headline:'बिजली खरीद का खर्च बताएगा, जेब पर पड़ेगा कितना असर', title:'Power-purchase costs and the impact on electricity bills', date:'14 July 2026', dateTime:'2026-07-14', image:'/images/nbt-electricity-procurement.jpeg', sideways:false, summary:'Navbharat Times reports on monthly PPAC reviews and their possible effect on Delhi electricity bills. The article also describes a reduction for Tata Power-DDL consumers in July 2026.', source:'Navbharat Times, New Delhi edition, page 5.' },
 { id:'monthly-review', headline:'‘बिजली की कीमत’ तय करेगी अब हर महीने आपका बिल', title:'Monthly PPAC reviews reported for Delhi consumers', date:'Date not visible in clipping', dateTime:undefined, image:'/images/nbt-ppac-monthly-review.jpeg', sideways:true, summary:'This brief report describes monthly review of power-purchase adjustment costs, previously reviewed every three months, and directs readers to the detailed report on page 5.', source:'Navbharat Times (NBT report), New Delhi. Page number and publication date are not visible.' },
];
export function NewsArchive(){
 return <div className="media-archive-grid">{articles.map(article=><article key={article.id} className="media-article"><Dialog><DialogTrigger asChild><button className="media-image-button" aria-label={`Read newspaper clipping: ${article.title}`}><div className={`media-image ${article.sideways?'sideways':''}`}><img src={article.image} alt={article.headline} width="899" height="1599" loading="lazy"/></div><span>Read newspaper clipping <ArrowUpRight size={16}/></span></button></DialogTrigger><DialogContent className="clipping-dialog"><DialogTitle>{article.title}</DialogTitle><DialogDescription>{article.source} {article.date}. Hindi.</DialogDescription><div className={`clipping-original ${article.sideways?'sideways':''}`}><img src={article.image} alt={article.headline} width="899" height="1599"/></div><a href={article.image} target="_blank" rel="noopener noreferrer" className="text-link">Open original photograph <ArrowUpRight size={17}/></a></DialogContent></Dialog><div className="media-article-copy"><div className="media-article-meta"><span>Media Coverage</span>{article.dateTime?<time dateTime={article.dateTime}>{article.date}</time>:<span>{article.date}</span>}</div><h3 lang="hi">{article.headline}</h3><p className="media-translation">{article.title}</p><p>{article.summary}</p><dl><div><dt>Publication</dt><dd>Navbharat Times</dd></div><div><dt>Language</dt><dd>Hindi</dd></div><div><dt>Original source</dt><dd>{article.source} Supplied newspaper photograph.</dd></div></dl></div></article>)}</div>;
}
