// Homepage copy and source-derived facts. Review before public launch.
export const society = {
  name: 'Delhi Fight Against Electricity Bills Society',
  caption: 'Governed by a private body/society.',
  registration: 'ROS/OUTER NORTH/2026/52',
  date: '20 July 2026',
  address: 'Plot No. 86, Pocket-C, Sector-2, DSIIDC Bawana, Delhi–110039',
};
export const navigation = [
  ['About', '#about'], ['Bill Help', '#bill-help'], ['Our Work', '#our-work'],
  ['Resources', '#resources'], ['Join Us', '#join'], ['Contact', '#contact'],
];
export const guides = [
  { title: 'Understand your bill', category: 'Start with the basics', description: 'Find the account details, billing period and payment information on your electricity bill.', paragraphs: ['Begin with the consumer or CA number, the billing period and the due date. Check that the bill belongs to the right account and period.', 'Keep a copy of the bill and compare the current and previous meter readings where they are shown. Bill layouts vary between providers.', 'The detailed guide will use an illustrative bill with numbered explanations. Provider-specific instructions will be reviewed before publication.'] },
  { title: 'Bill components', category: 'Know the terminology', description: 'Get familiar with energy charges, fixed charges, adjustments and previous balances.', paragraphs: ['A bill can contain several different components. Look for separate entries for energy consumption, fixed charges, adjustments and any previous balance.', 'Compare like-for-like billing periods and retain the original bill when asking about an unfamiliar entry.', 'Examples, rates and calculation methods will be added only with their applicable period and reviewed source.'] },
  { title: 'PPAC & FPPAS', category: 'Explore the context', description: 'Learn what to look for when reading information about power-purchase adjustments.', paragraphs: ['The meaning and application of these terms must be checked against the relevant provider and official order. They should not be assumed to be interchangeable.', 'A useful source identifies the provider, applicable consumer category and effective period. A historical news percentage is not necessarily a current rate.', 'This guide is reserved for a reviewed explanation with official references. No current rates are stated in this preview.'] },
  { title: 'Raising a grievance', category: 'Prepare your records', description: 'Organise your concern and distinguish a Society enquiry from a formal complaint.', paragraphs: ['Keep the relevant bill, payment records and earlier correspondence together. Write down the question you want answered and the dates involved.', 'Contacting the Society does not automatically file a complaint with an electricity provider, regulator or public authority.', 'The full guide will include verified official channels and reviewed process information. This preview does not set legal deadlines or prescribe a formal sequence.'] },
];
export const documents = [
  { title: 'Society registration certificate', category: 'Registration', date: '20 July 2026', description: 'Registration details and the Society’s recorded identity.', paragraphs: ['Registered name: DELHI FIGHT AGAINST ELECTRICITY BILLS SOCIETY.', 'Registration number: ROS/OUTER NORTH/2026/52. Certificate date: 20 July 2026. Working area: Delhi.', 'The specification transcribes the certificate as registration under the Societies Registration Act XXI of 1860, issued by the Registrar of Societies, District Outer North, Govt. of NCT of Delhi.', 'The original certificate must be checked before public publication. An approved certificate file has not yet been added to this homepage.'] },
  { title: 'Earlier initiative: association support letter', category: 'Historical record', date: '24 July 2024', description: 'A support record from the initiative that predates the registered Society.', paragraphs: ['The specification records a letter from the Patparganj F.I.E. Entrepreneurs Association (Regd.), reference MMM/2024/286, dated 24 July 2024.', 'The letter refers to a meeting on 18 July 2024. It relates to the earlier electricity-bill initiative, before the Society’s registration in 2026.', 'It should not be presented as a 2024 endorsement of the registered Society. The source file and approved public copy will be added after review.'] },
];
export const issuePreview = {title: 'Sharing a billing concern', paragraphs: ['Issue submissions are not open in this homepage preview. No information or files are collected here.', 'The planned form will ask for your contact details, locality, electricity provider, a description of the concern and optional supporting bill copies.', 'Do not send passwords, payment credentials or Aadhaar details. Contacting the Society will not automatically file a complaint with a provider or authority.']};
export const participation = [
  { title: 'Individual interest', description: 'Stay connected with the cause and express your interest in participating.', paragraphs: ['Individuals will be able to share their interest in the Society’s awareness and participation activities.', 'The planned enquiry will ask for contact details, locality and areas of interest. Sending an enquiry will not confer membership.', 'Participation forms are not collecting information in this homepage preview.'] },
  { title: 'Association collaboration', description: 'Explore a conversation on shared electricity-billing concerns.', paragraphs: ['Associations and organisations will be able to introduce themselves and describe the concerns they would like to discuss.', 'The planned enquiry will include organisation and contact details, locality and a message. No partnership is created automatically.', 'Collaboration enquiries are not open in this homepage preview.'] },
  { title: 'Volunteer interest', description: 'Offer your time and skills to support awareness and documentation.', paragraphs: ['The volunteer enquiry will provide space to describe interests, relevant skills and availability.', 'Roles and participation arrangements will need to be confirmed by the Society. No position is promised through an enquiry.', 'Volunteer enquiries are not open in this homepage preview.'] },
];
