import { ArrowUpRight } from 'lucide-react';
import { society, navigation } from '@/content/home';
import { InfoDialog } from './info-dialog';
const policies = [
    { title: 'Privacy', paragraphs: ['This homepage preview does not collect issue submissions, contact enquiries or uploads.', 'A full privacy notice will describe the operator, purposes, recipients, retention and deletion process before collection starts. Hosting access and service logs are subject to the hosting provider’s practices.'] },
    { title: 'Disclaimer', paragraphs: ['This homepage is a design and content preview. Organisational wording and source transcriptions require review before public launch.', 'Information is general and does not establish current electricity rates, legal deadlines, outcomes or legal advice. Contacting the Society is separate from filing a formal complaint.'] },
    { title: 'Accessibility', paragraphs: ['This homepage includes keyboard-operable navigation and dialogs, visible focus indicators and a responsive layout.', 'A full accessibility audit has not yet been completed. Tested limitations and a verified support contact will be included in the final accessibility statement.'] },
];
export function Footer() { return <footer id="contact" className="site-footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><strong>{society.name}</strong><p className="governance">{society.caption}</p><p>Working for awareness, transparency and representation in electricity billing.</p></div><div><h2>Explore</h2>{navigation.slice(0, 4).map(([label, href]) => <a href={href} key={href}>{label}</a>)}</div><div><h2>Get involved</h2><a href="#join">Ways to participate</a><a href="#share-concern">Sharing a concern</a><a href="#registration">Registration details</a></div><div className="address"><h2>Registered address</h2><p>{society.address}</p><p className="address-note">Visitor-office arrangements have not been confirmed.</p><a href="#main" className="back-top">Back to top <ArrowUpRight size={16} /></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {society.name}</span><div>{policies.map(p => <InfoDialog key={p.title} {...p} label={p.title} className="footer-policy" />)}</div></div><p className="imagery-note">Illustrative AI-generated imagery; not photographs of Society activities.</p></div></footer> }
